### PR TITLE
Improve add_host

### PR DESCRIPTION
**Pull request by scopenco**
Hello,

I'm trying to create Chef cookbook that will create/delete hosts, services in Icinga2 using API. I want to use your library but it has not enough functionality to cover the full set of attributes for host object. In this PR I've added all Hosts attributes and made the direct match of library options to icinga2 objects attributes.

### CODE REVIEW

**Comment by scopenco** [comment]
@coveralls any ideas how it can be improved?

**Comment by scopenco** [comment]
@coveralls any updates?

**Comment by bodsch** [comment]
sorry for my missing response.
I'm in the middle of preparing for the OSMC.

after the first look over it, it looks good! Thank you!

Could you put the PR against branch stable/1.0.0-beta1, please? then I can include it in the 1.0 release.

**Comment by scopenco** [comment]
I've created new PR https://github.com/bodsch/ruby-icinga2/pull/24 because it's too many changes between `master` and `stable/1.0.0-beta1`

**Pull request closed without merging**
